In [2]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime
import seaborn as sns
import plotly.express as px

In [3]:
df = pd.read_excel("C:\Surya\DA\Hackathons\Python Hackathon Dec2023\Exam Stress Final.xlsx",sheet_name=None)
grades=df['Grades']
demography=df['Demography']
eda=df['EDA']
hr=df['HR']
temp=df['Temp']
ibi=df['IBI']


Q1. Using the mean interbeat interval per minute, calculate the Root Mean Square of successive differences for any 30 minute interval and add this to IBI

In [3]:
ibi_mean = np.mean(ibi.IBI)
selected_interval = ibi.IBI[:30]
successive_diff = np.diff(selected_interval)
rmssd = np.sqrt(np.mean(successive_diff**2))
ibi_with_rmssd = ibi_mean + rmssd
print('RMSSD: ',ibi_with_rmssd)

RMSSD:  0.6549284511905323


Q7. "Using numpy functions, transpose and multiply the following arrays
a=np.arange(4).reshape(2,2)
b=np.arange(6).reshape(3,2) "

In [18]:
a = np.arange(4).reshape(2, 2)
b = np.arange(6).reshape(3, 2)
print("\n Array a:")
print(a)
print("\n Array b:")
print(b)
print("\nTransposed Array a:")
print(np.transpose(a))

print("\nTransposed Array b:")
print(np.transpose(b))

print("\nResult of Transposed Multiplication:")
print(np.dot(a_transposed, b_transposed))


 Array a:
[[0 1]
 [2 3]]

 Array b:
[[0 1]
 [2 3]
 [4 5]]

Transposed Array a:
[[0 2]
 [1 3]]

Transposed Array b:
[[0 2 4]
 [1 3 5]]

Result of Transposed Multiplication:
[[ 2  6 10]
 [ 3 11 19]]


Q8.Write a Python program to create an array of 5 integers and display the array items in reverse order

In [13]:
array1 = np.array([1, 2, 3, 4, 5])
print("Array Created:", array1)

rev_array1 = np.flip(array1)
print("\nArray in Reverse Order:", rev_array1)

Array Created: [1 2 3 4 5]

Array in Reverse Order: [5 4 3 2 1]


Q9. What was the average grade for all students in the final exam vs both midterms

In [16]:
average_grades_by_student = grades.groupby('Student_id').mean()

print("Average Grade for all Students:")
print(average_grades_by_student)

Average Grade for all Students:
            Midterm 1  Midterm 2  final
Student_id                             
S01              78.0       82.0  182.0
S02              82.0       85.0  180.0
S03              77.0       90.0  188.0
S04              75.0       77.0  149.0
S05              67.0       77.0  157.0
S06              71.0       64.0  175.0
S07              64.0       33.0  110.0
S08              92.0       88.0  184.0
S09              80.0       39.0  126.0
S10              89.0       64.0  116.0


In [8]:
current_year = datetime.now().year
demography['Age'] = current_year - demography['DOB'].dt.year
#print(demography['Age'])
print("DataFrame with Age:")
print(demography[['Student_id', 'First Name', 'Last Name', 'DOB', 'Age']])
demography.drop(columns=['DOB'], inplace=True)



DataFrame with Age:
  Student_id First Name  Last Name        DOB  Age
0        S01    Barbara    Walters 2009-01-01   14
1        S02       Nora      Jones 2009-02-02   14
2        S03    Gabriel    Willows 2009-07-12   14
3        S04       John        Doe 2009-09-09   14
4        S05       Jane        Doe 2009-05-06   14
5        S06        Pat     Murray 2008-04-04   15
6        S07      Roger  Frederick 2010-08-01   13
7        S08       John      Wills 2009-03-03   14
8        S09       Paul    Cartney 2009-10-23   14
9        S10     Janice      Smith 2009-11-14   14


In [9]:
print(demography)

  Student_id First Name  Last Name Gender     Race  Age
0        S01    Barbara    Walters      F    White   14
1        S02       Nora      Jones      F    White   14
2        S03    Gabriel    Willows      F    Asian   14
3        S04       John        Doe      M    Asian   14
4        S05       Jane        Doe      F  African   14
5        S06        Pat     Murray      M  African   15
6        S07      Roger  Frederick      M  African   13
7        S08       John      Wills      M    White   14
8        S09       Paul    Cartney      M    White   14
9        S10     Janice      Smith      F  Spanish   14


In [10]:
demography_original_df = excel_file.parse('Demography')

# Merge the original DataFrame with the one containing 'DOB'
merged_df = pd.merge(demography_original_df, demography_df[['Student_id', 'DOB']], on='Student_id', how='inner')

# Drop the 'Age' column
merged_df.drop(columns=['Age'], inplace=True)

# Display the final DataFrame without 'Age'
print("\nFinal DataFrame without 'Age' column:")
print(merged_df[['Student_id', 'First Name', 'Last Name', 'DOB']])

NameError: name 'excel_file' is not defined

In [20]:
print(demography)

  Student_id First Name  Last Name Gender     Race  Age
0        S01    Barbara    Walters      F    White   14
1        S02       Nora      Jones      F    White   14
2        S03    Gabriel    Willows      F    Asian   14
3        S04       John        Doe      M    Asian   14
4        S05       Jane        Doe      F  African   14
5        S06        Pat     Murray      M  African   15
6        S07      Roger  Frederick      M  African   13
7        S08       John      Wills      M    White   14
8        S09       Paul    Cartney      M    White   14
9        S10     Janice      Smith      F  Spanish   14


In [26]:
# Load your Excel file into a DataFrame
excel_file = pd.ExcelFile('C:\Surya\DA\Hackathons\Python Hackathon Dec2023\Exam Stress Final.xlsx')
demography_df = excel_file.parse('Demography')

# Print the columns of the DataFrame
print("Columns of the DataFrame:")
print(demography_df.columns)

# Calculate age based on the current date
current_year = datetime.now().year

# Assuming 'DOB' is part of the index, reset the index to make it a regular column
demography_df.reset_index(inplace=True)

# Now try calculating age again
demography_df['Age'] = current_year - demography_df['DOB'].dt.year

# Display the DataFrame with the calculated age and drop 'DOB'
print("DataFrame with Age (DOB dropped):")
print(demography_df)

# Drop the 'DOB' column
demography_df.drop(columns=['DOB'], inplace=True)
print(demography_df)

# Reload the original "Demography" DataFrame
demography_original_df = excel_file.parse('Demography')
print(demography_original_df)

# Merge the original DataFrame with the one containing 'DOB'
merged_df = pd.merge(demography_original_df, demography_df[['Student_id', 'DOB']], on='Student_id', how='inner')

# Drop the 'Age' column
merged_df.drop(columns=['Age'], inplace=True)

# Display the final DataFrame without 'Age'
print("\nFinal DataFrame without 'Age' column:")
print(merged_df[['Student_id', 'First Name', 'Last Name', 'DOB']])


Columns of the DataFrame:
Index(['Student_id', 'DOB', 'First Name', 'Last Name', 'Gender', 'Race'], dtype='object')
DataFrame with Age (DOB dropped):
   index Student_id        DOB First Name  Last Name Gender     Race  Age
0      0        S01 2009-01-01    Barbara    Walters      F    White   14
1      1        S02 2009-02-02       Nora      Jones      F    White   14
2      2        S03 2009-07-12    Gabriel    Willows      F    Asian   14
3      3        S04 2009-09-09       John        Doe      M    Asian   14
4      4        S05 2009-05-06       Jane        Doe      F  African   14
5      5        S06 2008-04-04        Pat     Murray      M  African   15
6      6        S07 2010-08-01      Roger  Frederick      M  African   13
7      7        S08 2009-03-03       John      Wills      M    White   14
8      8        S09 2009-10-23       Paul    Cartney      M    White   14
9      9        S10 2009-11-14     Janice      Smith      F  Spanish   14
   index Student_id First Name  Last

KeyError: "['DOB'] not in index"

Q11. What are the top 3 grades in the final exam? What % of the top 3 grades belonged to males vs females? 


In [32]:
merged_df = pd.merge(grades, demography, on='Student_id', how='inner')

top_3_final_grades = merged_df.nlargest(3, 'final')
print("Top 3 grades in final exam:\n")
print(top_3_final_grades[['Student_id', 'First Name', 'Last Name', 'Gender', 'final']])

# Calculate the percentage of top 3 grades belonging to males and females
total_top_3 = top_3_final_grades.shape[0]
male_percentage = (top_3_final_grades['Gender'].value_counts().get('M', 0) / total_top_3) * 100
female_percentage = (top_3_final_grades['Gender'].value_counts().get('F', 0) / total_top_3) * 100

print(f"\nMale percentage in Top 3: {male_percentage:.1f}%")
print(f"Female percentage in Top 3: {female_percentage:.1f}%")

Top 3 grades in final exam:

  Student_id First Name Last Name Gender  final
2        S03    Gabriel   Willows      F    188
7        S08       John     Wills      M    184
0        S01    Barbara   Walters      F    182

Male percentage in Top 3: 33.3%
Female percentage in Top 3: 66.7%


Q12. phonebook={"john":938477566,"Jack":938377264,"Jill":947662781}  ,find the phone number of Joe

In [36]:
phonebook = {"john": 938477566, "Jack": 938377264, "Jill": 947662781}

output = phonebook.get("Joe","Not Found")

print(output)

Not Found


Q13. How many minutes did the midterm 2 last( on average) for all 10 students


In [40]:
midterm2_df = eda[eda['Exam'] == 'midterm 2']
avg_time = midterm2_df['Time in mins'].mean()

print(f" Average duration of midterm-2 for all 10 students: {avg_time:.1f} minutes")

 Average duration of Midterm 2 for all 10 students: 102.6 minutes


In [46]:
# Calculate the percentage difference between Midterm1 and Final
grades['Midterm1_vs_Final'] = ((grades['final'] - grades['Midterm 1']) / grades['Midterm 1']) * 100
print(grades['Midterm1_vs_Final'])

# Calculate the percentage difference between Midterm2 and Final
grades['Midterm2_vs_Final'] = ((grades['final'] - grades['Midterm 2']) / grades['Midterm 2']) * 100

# Display the resulting DataFrame with the percentage differences
print("DataFrame with Percentage Differences:")
print(grades[['Student_id', 'Midterm1_vs_Final', 'Midterm2_vs_Final']])

0    133.333333
1    119.512195
2    144.155844
3     98.666667
4    134.328358
5    146.478873
6     71.875000
7    100.000000
8     57.500000
9     30.337079
Name: Midterm1_vs_Final, dtype: float64
DataFrame with Percentage Differences:
  Student_id  Midterm1_vs_Final  Midterm2_vs_Final
0        S01         133.333333         121.951220
1        S02         119.512195         111.764706
2        S03         144.155844         108.888889
3        S04          98.666667          93.506494
4        S05         134.328358         103.896104
5        S06         146.478873         173.437500
6        S07          71.875000         233.333333
7        S08         100.000000         109.090909
8        S09          57.500000         223.076923
9        S10          30.337079          81.250000


Q16. What was the % difference between scores in both mid-terms vs the final


In [57]:
avg_midterm = (grades['Midterm 1'] + grades['Midterm 2'])

grades['result'] = ((grades['final'] - avg_midterm) / avg_midterm) * 100
print("Percentage difference of grades in both Midterms Vs Final:")
print(grades[['Student_id','result']])

Percentage difference of grades in both Midterms Vs Final:
  Student_id     result
0        S01  13.750000
1        S02   7.784431
2        S03  12.574850
3        S04  -1.973684
4        S05   9.027778
5        S06  29.629630
6        S07  13.402062
7        S08   2.222222
8        S09   5.882353
9        S10 -24.183007
