In [38]:
import pandas as pd
!pip install matplotlib
import numpy as np
#pip install openpyxl

In [43]:
import pandas as pd
dataset_grades = pd.read_excel("~/Sharanya/Sharanya_Numpy/ExamStressFinal.xlsx", sheet_name="Grades")
dataset_demography = pd.read_excel("~/Sharanya/Sharanya_Numpy/ExamStressFinal.xlsx", sheet_name="Demography")
dataset_eda = pd.read_excel("~/Sharanya/Sharanya_Numpy/ExamStressFinal.xlsx", sheet_name="EDA")
dataset_hr = pd.read_excel("~/Sharanya/Sharanya_Numpy/ExamStressFinal.xlsx", sheet_name="HR")
dataset_temp = pd.read_excel("~/Sharanya/Sharanya_Numpy/ExamStressFinal.xlsx", sheet_name="Temp")
dataset_ibi = pd.read_excel("~/Sharanya/Sharanya_Numpy/ExamStressFinal.xlsx", sheet_name="IBI")

In [48]:
dataset_ibi.head()

Time in mins    IBI Student_id   Exam
0             0  0.446        S01  final
1             1  0.473        S01  final
2             3  0.444        S01  final
3             4  0.496        S01  final
4             8  0.448        S01  final

# Q65 Generate a 3x3  Array using Random values between 1to 9  and Fix the values and position  in Next Run.

In [64]:
#Generating the random array
random_int = np.random.randint(1,9,(3,3))
#printing the random array
print(random_int)

[[3 7 2]
 [1 5 7]
 [2 4 7]]


In [66]:
# set a seed for reproducibility
np.random.seed(10)
# generating the fixed array
fixed_array = np.random.randint(1, 10, size=(3, 3))
#printing the fixed array
print(fixed_array)

[[5 1 2]
 [1 2 9]
 [1 9 7]]


# Q66 Find the way to reverse string for given input (eg: input : this is python hackathon output:hackathon python is this)